### ISSUE TITLE
compiling error after goutil update

### ISSUE THREAD

**Issue by korsar4eg** [gookit/filter#66]
**System (please complete the following information):**

 - OS: `linux` 
 - 
**Describe the bug**

When building app getting 
# github.com/gookit/filter
/home/gitlab-runner/go/pkg/mod/github.com/gookit/filter@v1.2.0/converters.go:55:46: cannot use mathutil.ToUint(in) (value of type uint) as uint64 value in return statement

**Comment by inhere** [comment]
hi @korsar4eg Please upgrade gookit/filter to [v1.2.1](https://github.com/gookit/filter/releases/tag/v1.2.1)
